#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_sftp:
  path: /sftp
  controller: App\Controller\sftpController::sftpRender
app_sftp_connect:
  path: /connect
  controller: App\Controller\sftpController::connection